### ISSUE TITLE
Document a roadmap/plan

### ISSUE THREAD

**Issue by tylermumford** [peterhellberg/wiki#4]
Hey, this is a really nice, simple wiki. Thank you for creating it. 🙂 

I was hoping you could update the project's Readme, wiki, or another document with a roadmap or plan. I'm wondering what scope you want for this project, what kind of features you do or don't want to add/accept, and whether/how you want contributors to help. It's up to you, but I think it would help keep everyone on the same page.

**Comment by peterhellberg** [comment]
@tylermumford Hello, I'm sorry that I haven't replied earlier.

There isn't much of a roadmap or plan for this project, it was just meant to be a simple example application. I don't expect to add any (major) features to this project.

**Comment by tylermumford** [comment]
Okay, thank you for responding and clarifying that. 👍
